version: '3.9'

services:
  php:
    build:
      context: .docker/
      dockerfile: php.Dockerfile
    volumes:
      - ./:/var/www/html
    user: "1000"
    environment:
      - APP_ENV=local
    networks:
      - the_test_network
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    networks:
      - the_test_network

  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www/html
      - .docker/nginx-default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - php
    networks:
      - the_test_network

volumes:
  mysql_data:

networks:
  the_test_network:
